#!/bin/bash

# GLOBAL VARS
#  SETUP_PATH
#  WORKSPACE_PATH

# LOCAL VARS
GO_VERSION_INSTALL=1.25.1
FILENAME=go${GO_VERSION_INSTALL}.linux-amd64.tar.gz
DOWNLOAD_URL=https://go.dev/dl/${FILENAME}
DOWNLOAD_PATH=${SETUP_PATH}/GoArchives/${GO_VERSION_INSTALL}
INSTALL_PATH=${WORKSPACE_PATH}/Go/${GO_VERSION_INSTALL}
PATH=$PWD:$PATH
echo $PATH

#  download and extract node
mkdir -p $DOWNLOAD_PATH
cd $DOWNLOAD_PATH
pwd
wget $DOWNLOAD_URL
extract.sh -i $FILENAME -o $INSTALL_PATH